### ISSUE TITLE
Remove deprecated OpenSearch values

### ISSUE THREAD

**Issue by dlvenable** [opensearch-project/data-prepper#1648]
**Is your feature request related to a problem? Please describe.**

The OpenSearch sink has two values which were deprecated: `trace_analytics_raw` and `trace_analytics_service_map`. The `index_type` field replaces these.

**Describe the solution you'd like**

Remove `trace_analytics_raw` and `trace_analytics_service_map` from the OpenSearch sink.

**Tasks**

- [x] Remove `trace_analytics_raw` and `trace_analytics_service_map` from Data Prepper (#1690)
- [x] Update OpenSearch documentation website regarding this change (https://github.com/opensearch-project/documentation-website/pull/1029)

**Comment by oeyh** [comment]
Two tasks for this issue:

- [ ] Remove `trace_analytics_raw` and `trace_analytics_service_map` from Data Prepper
- [ ] Update OpenSearch documentation website regarding this change
