### ISSUE TITLE
[RFC] Directory Structure for Data Prepper

### ISSUE THREAD

**Issue by dlvenable** [opensearch-project/data-prepper#305]
This RFC introduces a change from distributing Data Prepper as an uber-jar into a bundled directory structure. This approach is similar to how OpenSearch is distributed.

## What is the problem? What is preventing you from meeting the requirements?

Data Prepper distributes its code in a single uber-jar. We are planning work to support extending Data Prepper with custom plugins. This requires that we have a location for loading additional jar files which are not part of the uber-jar. Additionally, those plugins will be decoupled from data-prepper-core, which means we will have multiple jar files.

## What are you proposing? What do you suggest we do to solve the problem or improve the existing situation?

We propose distributing Data Prepper as a bundle which must be extracted into a directory structure. Data Prepper will now include a shell script for starting Java with the required classpath.

### User Experience

Users can deploy Data Prepper using the following options:

* Run the Docker container
* Install Bundled Distribution
* Build from source

#### Docker

Users deploying using Docker currently run the following commands.

```
docker pull opensearchproject/data-prepper:latest
docker run --name data-prepper --expose 21890 -v /full/path/to/pipelines.yaml:/usr/share/data-prepper/pipelines.yaml -v /full/path/to/data-prepper-config.yaml:/usr/share/data-prepper/data-prepper-config.yaml opensearchproject/data-prepper:latest
```

This proposal will slightly alter the process by changing linked files.

| Original Destination                                               	| Updated Destination |
| -------------------------------------------------- | --------------------------------------------------------- |
| /usr/share/data-prepper/pipelines.yaml	                | /usr/share/data-prepper/pipelines/pipelines.yaml                |
| /usr/share/data-prepper/data-prepper-config.yaml	| /usr/share/data-prepper/config/data-prepper-config.yaml |

The new commands will be:

```
docker pull opensearchproject/data-prepper:latest
docker run --name data-prepper --expose 21890 -v /full/path/to/pipelines.yaml:/usr/share/data-prepper/pipelines/pipelines.yaml -v /full/path/to/data-prepper-config.yaml:/usr/share/data-prepper/config/data-prepper-config.yaml opensearchproject/data-prepper:latest
```

#### Install Bundled Distribution

Users who installed our bundled distribution get a single uber-jar. Because this uber-jar has everything bundled, users run Data Prepper with the following command.

```
java -jar data-prepper-core-$VERSION.jar pipelines.yaml data-prepper-config.yaml
```

With the proposed update, users will install Data Prepper by performing steps similar to the following.

```
cd path/to/parent/directory
wget https://.../path/to/data-prepper-$VERSION.tar.gz
tar -xf data-prepper-$VERSION.tar.gz
```

Users can then run Data Prepper with the following commands.

```
cd data-prepper-$VERSION
bin/data-prepper
```

### Proposed Structure

Below is the initial directory structure which this change will introduce.

```
data-prepper-$VERSION/
  bin/
    data-prepper                    # Shell script to run Data Prepper on Linux/macOS
  config/
    data-prepper-config.yaml        # The Data Prepper configuration file
    log4j.properties                # Logging configuration
  pipelines/                             # New directory for pipelines
    trace-analytics.yaml
    log-ingest.yaml
  lib/
    data-prepper-core.jar
    ... any other jar files
  logs/                             # Directory for log output
  LICENSE
  NOTICE
  README.md
```

The proposed structure is similar to OpenSearch’s directory structure. 

## What are your assumptions or prerequisites?

This RFC is limited in scope to the change to deploying with a directory structure. It does not include details for any features which depend on this.

Future features may expand the proposed directory structure. This approach does not attempt to foresee every possible directory.

Users still continue to provide the pipeline configuration file to Data Prepper as a command-line argument.

We expect that users only need to run Data Prepper on Linux. This proposal does not include a Windows script, which would likely be `bin/data-prepper.bat`. However, this could be included into this approach if requested.

Additional changes

In addition to deploying with a directory structure, this includes other related changes.

* Data Prepper can read the config file located at `config/data-prepper-config.yaml` rather than require it as a command-line argument.
* Data Prepper will expose the Log4j logging configuration file. This can be a clearer approach than requiring users to override a Java property.
* Data Prepper will write logs to the `logs/` directory.

# Tasks

- [x] #1655 
- [x] Update archive structure to include script
- [x] Break apart `data-prepper-core` and deploy jar files in to `lib/` directory
- [x] Add `data-prepper-main`
- [x] #1728
- [x] #1736
- [x] Update smoke tests to copy configuration files and pipelines to the correct locations
- [x] #1762
- [x] #1785
- [x] #1795

**Comment by dlvenable** [comment]
I'd also like to propose that Data Prepper run all pipelines from a pipelines directory.

For example:

```
data-prepper-$VERSION/
  bin/
    data-prepper                  # Shell script to run Data Prepper on Linux/macOS
  pipelines/                          # New directory for pipelines
    trace-analytics.yaml
    log-ingest.yaml
  ...                                        # Other files and directories
```

With this change, users can run Data Prepper by running:

```
bin/data-prepper
```

Data Prepper would then read the `pipelines/` directory for YAML files. It will parse each one and start the pipelines defined in all those configurations.
