### ISSUE TITLE
Update Java support

### ISSUE THREAD

**Issue by dlvenable** [opensearch-project/data-prepper#3192]
## Background

Data Prepper uses the Temurin releases for packages with bundled JDKs. Temurin has active LTS support for both Java 11 and 17. Java 21 is planned is a planned LTS release coming in Sep 2023.

## Proposal

Update Data Prepper's supported Java versions to 21 and 17. As a breaking change, Data Prepper can stop supporting Java 11 entirely. This also means that developers can start using features which are available only in Java 17 and above.

We can also run some performance tests against Java 21 after it is released. This can help us determine if the default bundled JDK should be 21 instead of 17. Previously we found a performance gain running on Java 17 over 11 which motivated the update to bundle 17 instead.

Additionally, the Data Prepper builds can start to run against the latest non-LTS release to ensure forward compatibility with upcoming versions. This is presently Java 20.

## Tasks

- [ ] Start building Data Prepper on Java 20
- [ ] Performance evaluation of Data Prepper on Java 21 (once available)
- [ ] Bundle Data Prepper with Java 21 (once available; possibly breaking change)
- [ ] Update the minimum version of Data Prepper to 17 (breaking change)

## Reference

https://adoptium.net/support/

**Comment by erzohrakhan** [comment]
@dlvenable I can help you with this;

**Comment by dlvenable** [comment]
@erzohrakhan , Thank you for your help here. As you can see in the description we have a list of tasks to accomplish.

The first item will probably be to get the tests running on Java 20. I've not tried it locally, but you can try that and make any necessary changes. Once it works locally a PR to add it into the matrix below would be good.

https://github.com/opensearch-project/data-prepper/blob/90575b1de56f82f44d1af36f31ff4b077a627bd7/.github/workflows/gradle.yml#L15

I think the other items we will need to wait on, though Java 21 is scheduled for Sep 19. Also, it sounds like Gradle 8.3 does not yet support Java 21.

https://docs.gradle.org/current/userguide/compatibility.html

**Comment by dlvenable** [comment]
@erzohrakhan , If you'd like to help here, the next good task may be updating to Gradle 8.4 and running against Java 21 now that it is available.

**Comment by dlvenable** [comment]
I'd like to propose that by Data Prepper 3.0 we only support Java 21. That is, we drop support for Java 17 entirely. Java 21 is almost a year old and likely by the time we release 3.0 it will have been over a year.
