### ISSUE TITLE
Deploy Artifacts to Maven Central

### ISSUE THREAD

**Issue by dlvenable** [opensearch-project/data-prepper#421]
**Is your feature request related to a problem? Please describe.**

Building an external plugin requires having data-prepper-api. Presently, this is not available unless it is manually built by a plugin author.

We should deploy Data Prepper artifacts to Maven Central.

Additionally, we deploy to the Maven groupId: `org.opensearch.dataprepper`. Since this project is not currently deployed, this is not a breaking change.

**Describe the solution you'd like**

Deploy aftifacts to Maven Central

**Additional context**

This is important to fully support to #321 .

# Tasks

* [x] Update groupId to `org.opensearch.dataprepper`
* [x] Support publication of Maven artifacts to Maven local
* [x] #1180
* [x] https://github.com/opensearch-project/opensearch-build/issues/1751

**Comment by dlvenable** [comment]
The release will be supported by the work planned in #977.

**Comment by dlvenable** [comment]
The Data Prepper Release GitHub Action is deploying the following Maven artifacts:

```
/
  {version}/
    {buildNumber}/
      maven/
        org/opensearch/dataprepper/
          data-prepper-api/
            maven-metadata.xml
            {version}/
              data-prepper-api-{versionIdentifier}-javadoc.jar
              data-prepper-api-{versionIdentifier}.jar
              data-prepper-api-{versionIdentifier}.pom
              data-prepper-api-{versionIdentifier}-sources.jar
              data-prepper-api-{versionIdentifier}.module
              maven-metadata.xml
```

For release builds, the `versionIdentifier` is equal to the `version`. For `SNAPSHOT` builds, the `versionIdentifier` will have a unique identifier added to it. This identifier is based on the timestamp, but the exact format doesn't matter. The `maven-metadata.xml` file will include the `versionIdentifer` values.

In addition, each file has the following four checksums:

* `md5`
* `sha1`
* `sha256`
* `sha512`
