### ISSUE TITLE
Support AWS Aurora/RDS MySQL as source

### ISSUE THREAD

**Issue by oeyh** [opensearch-project/data-prepper#4561]
**Is your feature request related to a problem? Please describe.**
As a Data Prepper user, I would like to have an `rds` source to load existing data and stream change events from RDS MySQL databases.

**Describe the solution you'd like**
For export (loading existing data), we can create a snapshot, export it to S3 and read the data from S3
For stream (streaming change events), we can connect to MySQL's binary log stream to receive change events.

**Describe alternatives you've considered (Optional)**
Run SQL queries periodically through a JDBC driver to load existing and incremental data from the source database. 

**Additional context**
The feature shares similar ideas with existing `dynamodb` source and `documentdb` source.

## Tasks

- [x] Project setup, source configurations, skeleton code
- [x] Export implementation - create snapshot and export to S3
- [x] Export implementation- read exported data files in S3
- [x] Stream implementation
- [x] Checkpointing in both export and stream
- [x] Pipeline configuration transformation template
- [x] Secret rotation support
- [x] Add E2E acknowledge support
- [x] Add data type mapping
- [x] Add plugin metrics
- [ ] Add aggregate metrics
- [ ] Add integration tests
