### ISSUE TITLE
Improved Plugin Configurations

### ISSUE THREAD

**Issue by dlvenable** [opensearch-project/data-prepper#469]
# Is your feature request related to a problem? Please describe.

There are a few problems with our plugin code:
* Each plugin has to translate between `PluginSetting` and an internal model. This is mostly tedious work.
* The `PluginSetting` class is somewhat overloaded. This likely because it is the one class which can be injected into new plugin instances.
* Plugin validation is manual.
* All plugins must take a `PlugginSetting` even if it is not used (this is not too big of a deal since it only comes up for smaller plugins).

# Describe the solution you'd like

At a high level, I'd like for plugins to be able to define POJO classes which represent their settings models.

This could be done by adding a new field to the `@DataPrepperPlugin` annotation:

```
Class<?> pluginConfigurationType() default PluginSetting.class;
```

Plugins can still get a `PluginSetting` class (that is the default value). But, they could also have related POJOs which are set in there. Then Data Prepper Core performs a Jackson conversion.

(I have already implemented this behavior and it is working well for simple cases)

Building on top of this design, I'd also like to make a few other changes:

### Split up PluginSetting

The `PluginSetting` class has two methods which can be extracted: `getName()` and `getPipelineName()`. I believe these are really not so much settings as they are metadata which is needed later.

I propose a new interface:

```
public interface PluginDescription {
  String getName();
  String getPipelineName();
}
```

The existing `PluginSetting` can implement this since it already provides these methods.

I'd like to find code that uses only these two methods and change that code to take in a `PluginDescription` instead. Here is one example:

```
public static PluginMetrics fromPluginSetting(final PluginSetting pluginSetting)
```

It only needs the name and pipelineName. So the signature could become:

```
@Deprecated
public static PluginMetrics fromPluginSetting(final PluginSetting pluginSetting) {
 ...
}
public static PluginMetrics fromPluginDescription(final PluginDescription pluginDescription) {
  ...
}
```

I think it would be good to also revisit the `getProcessWorkers()` method. This one makes a little more sense since it is defined by the pipeline configuration. But, it still isn't technically a plugin setting.

### Support Alternate Constructors

Right now plugins must have a constructor which takes only a `PluginSetting` object.

I propose that Data Prepper has a new annotation to indicate which constructor to use. This could be `@DataPrepperPluginConstructor`. I also think it is valuable to consider using JSR-330's `@Inject` annotation rather than create our own. But, even with our own annotation, it is very simple.

The approach for choosing a constructor would then become:

1. Look for the annotated constructor. Use this if found
2. Look for a constructor which takes `PluginSetting`. Use this if found. This is the existing behavior, so Data Prepper should continue to handle it. I think it should be deprecated behavior in v2.0.
3. Choose the default constructor if none of the others are available. Use it.

For the annotated constructor, Data Prepper should be able to populate any of the following types:
* `PluginDescription`
* `PluginSetting`
*  The class defined by `DataPrepperPlugin::pluginConfigurationType`

I would also like to consider supporting passing in the following classes into the constructor:
* `PluginMetrics`

If Data Prepper supports dependency injection, Data Prepper could also pass in other beans which are defined.

### Settings Validation

I'd like to add JSR 303 Bean Validation to these model classes. 

Plugin authors could make their POJOs look like the following:

```
class HttpSourceConfig {
  @Min(0)
  @Max(65535)
  private int port = 2021;

  @Min(0)
  private int requestTimeout = 10_000;
  ...
}
```

This isn't strictly necessary since constructors could still run validation manually.

Data Prepper could use the Hibernate Validator project which is Apache 2.0 licensed and is the reference implementation for JSR 303.

# Additional context

This largely came up because now I want to inject plugins into plugins. I could add more fields to `PluginSetting`, but this would just continue Data Prepper down this path of stuffing fields onto `PluginSettings`.

# Tasks

* [x] Support a custom plugin configuration type
* [x] Support for `@DataPrepperPluginConstructor`
* [x] JSR-303 bean validation of plugin configuration objects

**Comment by dlvenable** [comment]
This proposal was completed with the JSR-303 work done in #709.
