### ISSUE TITLE
Distribute Data Prepper Docker image with JDK 17

### ISSUE THREAD

**Issue by dlvenable** [opensearch-project/data-prepper#694]
**Is your feature request related to a problem? Please describe.**

The Data Prepper Docker image should include Corretto JDK 17 since it is an LTS version. The current Data Prepper Docker image includes Corretto 15. The tar.gz archive with JDK is also using JDK 15.

**Describe the solution you'd like**

Distribute Data Prepper Docker images with Amazon Corretto 11.

**Describe alternatives you've considered (Optional)**

Data Prepper could include AdoptOpenJDK 17 instead.

Data Prepper could use JDK 11 which is also LTS. However, we have found that simply updating to JDK 17 provides a performance improvement.

**Tasks**

* [ ] Update the Docker image
* [ ] Update the JDK which is installed in the tar.gz archive file
* [ ] Update example Docker images

**Comment by dlvenable** [comment]
This is probably something that should be worked after #665. At that point, the Gradle build and the Docker image will be using the same Java version.

**Comment by dlvenable** [comment]
OpenSearch distributes with [Temurin](https://adoptium.net) for the JDK. Absent a specific need to support Corretto, I suggest that we also distribute with Temurin. This is a slight change from the original proposal.

@oeyh

**Comment by dlvenable** [comment]
Temurin plans to support Java 17 through at least Oct 2027. Corretto has an end of life of Oct 2029. Both dates are sufficiently far in the future to where I don't see any benefit there.

https://adoptium.net/support/

https://aws.amazon.com/corretto/faqs/
