### ISSUE TITLE
Support Dependency Injection in Plugins

### ISSUE THREAD

**Issue by dlvenable** [opensearch-project/data-prepper#929]
**Is your feature request related to a problem? Please describe.**

Plugins currently do not use dependency injection. Data Prepper doesn't currently have a mechanism to allow plugin authors to create their own beans/objects to inject into plugin classes.

**Describe the solution you'd like**

Expand the support of the new Data Prepper Core DI injection using Spring so that plugins can use them.

The most important requirement is that plugin authors should be able to define an Application Context for their plugins. Optionally, Data Prepper could have a common Application Context which provides common beans to both Core and Plugins. But, this is something that could be added when a need arises.

The diagram below outlines the proposal.

![ApplicationContextsConcept-OptionB](https://user-images.githubusercontent.com/293424/150377706-841aaa20-1afb-49ec-a911-8d93b1a0aee3.png)

* Custom Plugin - A custom plugin. These could be existing plugins like grok, otel-trace-source, and others. It also includes plugins that would be defined in outside of the project.
* Plugin-Defined Application Context - An Application Context defined by plugin authors and part of the plugin project. It defines the beans that are needed for the plugin. Additionally, the plugin framework can dynamically add beans such as the current plugin configuration, plugin metrics.
* Plugin Factory - The existing plugin factory and framework. This framework will provide additional beans to the Plugin-Defined Application Context.
* Common Application Context - This is the optional shared Application Context which is available to all plugins and core. This would be defined in Data Prepper Core and available to plugins.
* Core-Only Application Context - The application contexts which are currently underway. These are beans available only to core classes.

**Describe alternatives you've considered (Optional)**

I considered an option where the Plugin Factory provides its objects directly to the plugin classes. In this approach, there would not be any beans for classes like Plugin Configuration. But, this approach means only the top-level plugin class can get these objects.

**Additional context**

Builds on #664.

**Tasks**

* [x] Support a common application context that is available to Core and plugins. This is completed by PR #1140.
* [ ] Allow plugins to define their own custom Application Context
* [ ] Allow plugin Application Contexts to load common beans
