### ISSUE TITLE
Data Prepper Build & Release Process

### ISSUE THREAD

**Issue by dlvenable** [opensearch-project/data-prepper#977]
# Summary

The Data Prepper maintainers would like to produce Data Prepper releases more often and reduce the friction with releasing them.

The approach to this goal will be to provide two CI/CD jobs.

1. Data Prepper Build
2. Data Prepper Promotion/Release

The first job can run either as a GitHub Action or as part of the OpenSearch build infrastructure. The second job must be part of the OpenSearch build infrastructure since it relies on signing and upload keys.

The following diagram outlines the high-level approach to building and releasing Data Prepper.

![Release-HighLevel](https://user-images.githubusercontent.com/293424/155164799-80f3f243-a657-4119-a78d-c3fe105f2e40.png)

## Data Prepper Artifacts

Data Prepper must produce the following artifacts as part of the release process.

* Data Prepper Docker image on DockerHub
* Linux archive distribution (.tar.gz) via [opensearch.org](http://opensearch.org/)
* Java libraries on Maven Central

In the future Data Prepper may include other platform distributions such as macOS or Windows. That is beyond the current scope however.

## Data Prepper Build

The Data Prepper Build job will be maintained and run by the Data Prepper maintainers. It will produce artifacts into repositories which are owned by the Data Prepper maintainers.

The Data Prepper maintainers will own two repositories:
* An S3 bucket for .tar.gz and Maven artifacts.
* An AWS ECR repository for Docker images

The job will have the following steps:

![DataPrepperRelease-PrimaryJob](https://user-images.githubusercontent.com/293424/152449580-0722d140-22c6-4cdb-a306-f946a728989d.png)

### Output Directory Structure

The following is an example directory structure for the artifacts.

```
/
  1.3.0/
    {buildNumber}/
      archive/
        opensearch-data-prepper-1.3.0-linux-x64.tar.gz
        opensearch-data-prepper-jdk-1.3.0-linux-x64.tar.gz
      maven/
        org/opensearch/dataprepper/
          data-prepper-api/
            maven-metadata.xml
            1.3.0/
              data-prepper-api-1.3.0-javadoc.jar
              data-prepper-api-1.3.0.jar
              data-prepper-api-1.3.0.pom
              data-prepper-api-1.3.0-sources.jar
              data-prepper-api-1.3.0.module
              maven-metadata.xml
```

## Data Prepper Promotion/Release

The Promotion/Release job will be part of the OpenSearch infrastructure. It will download the artifacts from the Build. It then signs them and uploads them to the final OpenSearch distribution repositories.

This job must be parameterized. It will take the following parameters:
* `versionNumber` - The version number to promote
* `sourceBuildNumber` - The build number of the source job which produced the artifacts for promotion

The job can be visualized as having the following steps:

![DataPrepperRelease-PromotionJob](https://user-images.githubusercontent.com/293424/152446873-1f758e1a-92ff-436e-9fa4-ce06d269f15b.png)

This job will be a Jenkins job running on the OpenSearch infrastructure. The Data Prepper maintainers will be the primary authors, but collaborate with the OpenSearch infrastructure maintainers on the job.

**Manual Steps**: I believe that currently there is a manual step to migrate from the Sonatype staging repository into Maven Central. If this is not necessary, then this job can be updated accordingly.

## Tasks

- [x] Investigate GitHub Actions for the primary job
- [x] Confirm approach with OpenSearch infrastructure maintainers
- [x] Setup necessary infrastructure; in particular the ECS repository
- [x] #1149
- [x] https://github.com/opensearch-project/opensearch-build/issues/1594
- [x] https://github.com/opensearch-project/opensearch-build/issues/1737
- [x] Document release process

**Comment by peternied** [comment]
Lets work together on some parts of this, I'm using data-prepper for our POC https://github.com/opensearch-project/opensearch-build/issues/1539

**Comment by peternied** [comment]
Here is a proof of concept for the new release model using data prepper, we should review this together and see how we can fill some of the design gaps between our systems https://github.com/peternied/data-prepper/pull/1/files
